### ISSUE TITLE
Ошибка парсинга ренджа в гугл апи

### ISSUE THREAD

**Issue by darksidersstrife** [kysect/Shreks#357]
Гугл апи спотыкается на таком:
Google.Apis.Requests.RequestError
Invalid data[0]: Unable to parse range: 'Лабораторные'!A1 [400]
Errors [
        Message[Invalid data[0]: Unable to parse range: 'Лабораторные'!A1] Location[ - ] Reason[badRequest] Domain[global]
]

at FluentSpreadsheets.GoogleSheets.Rendering.GoogleSheetComponentRenderer.UpdateValueRangesAsync(String spreadsheetId, IList`1 valueRanges, CancellationToken cancellationToken)
   at FluentSpreadsheets.GoogleSheets.Rendering.GoogleSheetComponentRenderer.RenderAsync(GoogleSheetRenderCommand command, CancellationToken cancellationToken)
   at Kysect.Shreks.Integration.Google.Sheets.LabsSheet.UpdateAsync(String spreadsheetId, CoursePointsDto points, CancellationToken token) in /source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets
/LabsSheet.cs:line 43

**Comment by Mihinator3000** [comment]
Это в дискорде вроде обсудили уже
